import type { Lead } from '../components/LeadCard'

export const mockLeadsData: Lead[] = [
  // New Leads
  {
    id: '1',
    name: 'Robert Johnson',
    email: 'robert.j@email.com',
    phone: '(555) 111-2222',
    address: '123 Oak Street',
    city: 'Springfield',
    state: 'IL',
    service: 'Flooring Installation',
    source: 'Google Search',
    requirement: 'New hardwood flooring for living room',
    budget: 5000,
    status: 'new',
     tags: ["Hot"],
    createdAt: '2026-01-28',
  },
  {
    id: '2',
    name: 'Patricia Smith',
    email: 'patricia.s@email.com',
    phone: '(555) 222-3333',
    address: '456 Elm Avenue',
    city: 'Chicago',
    state: 'IL',
    service: 'Carpet Cleaning',
    source: 'Referral',
    requirement: 'Professional carpet cleaning service',
    budget: 800,
    status: 'contacted',
     tags: ["Follow-up"],
    createdAt: '2026-01-27',
  },
  {
    id: '3',
    name: 'Christopher Lee',
    email: 'c.lee@email.com',
    phone: '(555) 333-4444',
    address: '789 Pine Road',
    city: 'Aurora',
    state: 'IL',
    service: 'Tile Restoration',
      type: 'Tile Restoration',
    source: 'Website',
    requirement: 'Bathroom tile repair and grout cleaning',
    budget: 3500,
    status: 'new',
    createdAt: '2026-01-26',
  },
  {
    id: '4',
    name: 'Jennifer Brown',
    email: 'jen.brown@email.com',
    phone: '(555) 444-5555',
    address: '321 Maple Drive',
    city: 'Naperville',
    state: 'IL',
    service: 'Flooring Repair',
    type:"Flooring Repair",
    source: 'Phone',
    requirement: 'Fix squeaky wooden floors',
    budget: 1200,
    status: 'qualified',
    createdAt: '2026-01-25',
  },
  {
    id: '5',
    name: 'Michael Davis',
    email: 'mdavis@email.com',
    phone: '(555) 555-6666',
    address: '654 Cedar Lane',
    city: 'Evanston',
    state: 'IL',
    service: 'Installation & Repair',
    source: 'Social Media',
    requirement: 'Laminate flooring installation',
    budget: 2800,
    status: 'contacted',
    createdAt: '2026-01-24',
  },
  {
    id: '6',
    name: 'Sarah Wilson',
    email: 'sarah.w@email.com',
    phone: '(555) 666-7777',
    address: '987 Birch Court',
    city: 'Oak Park',
    state: 'IL',
    service: 'Maintenance',
    source: 'Previous Customer',
    requirement: 'Regular floor maintenance plan',
    budget: 500,
    status: 'proposal-sent',
    createdAt: '2026-01-23',
  },
  {
    id: '7',
    name: 'David Martinez',
    email: 'dmartinez@email.com',
    phone: '(555) 777-8888',
    address: '147 Walnut Street',
    city: 'Skokie',
    state: 'IL',
    service: 'Flooring Installation',
    source: 'Yelp',
    requirement: 'Vinyl plank flooring for kitchen',
    budget: 3200,
    status: 'qualified',
    createdAt: '2026-01-22',
  },
  {
    id: '8',
    name: 'Emily Taylor',
    email: 'emily.t@email.com',
    phone: '(555) 888-9999',
    address: '258 Hickory Road',
    city: 'Wheaton',
    state: 'IL',
    service: 'Carpet Cleaning',
    source: 'Google Search',
    requirement: 'Deep carpet cleaning for office',
    budget: 1500,
    status: 'follow-up',
    createdAt: '2026-01-21',
  },
  {
    id: '9',
    name: 'James Anderson',
    email: 'james.a@email.com',
    phone: '(555) 999-0000',
    address: '369 Spruce Way',
    city: 'Des Plaines',
    state: 'IL',
    service: 'Tile Restoration',
    source: 'Referral',
    requirement: 'Kitchen backsplash installation',
    budget: 4500,
    status: 'closed-won',
    createdAt: '2026-01-20',
  },
  {
    id: '10',
    name: 'Lisa Anderson',
    email: 'lisa.a@email.com',
    phone: '(555) 000-1111',
    address: '741 Oak Lane',
    city: 'Mount Prospect',
    state: 'IL',
    service: 'Flooring Repair',
    source: 'Website',
    requirement: 'Water damaged floor replacement',
    budget: 6200,
    status: 'closed-won',
    createdAt: '2026-01-19',
  },
  {
    id: '11',
    name: 'Thomas Garcia',
    email: 'tgarcia@email.com',
    phone: '(555) 111-2222',
    address: '852 Cherry Street',
    city: 'Schaumburg',
    state: 'IL',
    service: 'Installation & Repair',
    source: 'Phone',
    requirement: 'Commercial flooring assessment',
    budget: 8000,
    status: 'new',
    createdAt: '2026-01-18',
  },
  {
    id: '12',
    name: 'Maria Rodriguez',
    email: 'mrodriguez@email.com',
    phone: '(555) 222-3333',
    address: '963 Maple Court',
    city: 'Arlington Heights',
    state: 'IL',
    service: 'Maintenance',
    source: 'Referral',
    requirement: 'Quarterly maintenance contract',
    budget: 400,
    status: 'proposal-sent',
    createdAt: '2026-01-17',
  },
  {
    id: '13',
    name: 'Charles Thompson',
    email: 'cthompson@email.com',
    phone: '(555) 333-4444',
    address: '159 Ash Drive',
    city: 'Rosemont',
    state: 'IL',
    service: 'Carpet Cleaning',
    source: 'Google Search',
    requirement: 'Hotel carpet cleaning service',
    budget: 2200,
    status: 'closed-lost',
    createdAt: '2026-01-16',
  },
  {
    id: '14',
    name: 'Michelle White',
    email: 'mwhite@email.com',
    phone: '(555) 444-5555',
    address: '753 Elm Street',
    city: 'Park Ridge',
    state: 'IL',
    service: 'Flooring Installation',
    source: 'Website',
    requirement: 'Master bedroom new flooring',
    budget: 3800,
    status: 'follow-up',
    createdAt: '2026-01-15',
  },
  {
    id: '15',
    name: 'Daniel Harris',
    email: 'dharris@email.com',
    phone: '(555) 555-6666',
    address: '951 Oak Street',
    city: 'Palatine',
    state: 'IL',
    service: 'Tile Restoration',
    source: 'Previous Customer',
    requirement: 'Bathroom tile renovation',
    budget: 5500,
    status: 'contacted',
    createdAt: '2026-01-14',
  },
  {
    id: '16',
    name: 'Barbara Martinez',
    email: 'bmartinez@email.com',
    phone: '(555) 666-7777',
    address: '456 Pine Lane',
    city: 'Barrington',
    state: 'IL',
    service: 'Other',
    source: 'Yelp',
    requirement: 'Consult on floor options',
    budget: 0,
    status: 'new',
    createdAt: '2026-01-13',
  },
  {
    id: '17',
    name: 'Richard Clark',
    email: 'rclark@email.com',
    phone: '(555) 777-8888',
    address: '789 Birch Avenue',
    city: 'Buffalo Grove',
    state: 'IL',
    service: 'Installation & Repair',
    source: 'Social Media',
    requirement: 'Office flooring upgrade',
    budget: 7000,
    status: 'qualified',
    createdAt: '2026-01-12',
  },
  {
    id: '18',
    name: 'Karen Lee',
    email: 'klee@email.com',
    phone: '(555) 888-9999',
    address: '654 Cedar Road',
    city: 'Deerfield',
    state: 'IL',
    service: 'Maintenance',
    source: 'Google Search',
    requirement: 'Annual floor polishing',
    budget: 600,
    status: 'closed-won',
    createdAt: '2026-01-11',
  },
  {
    id: '19',
    name: 'Steven Walker',
    email: 'swalker@email.com',
    phone: '(555) 999-0000',
    address: '321 Hickory Lane',
    city: 'Northbrook',
    state: 'IL',
    service: 'Carpet Cleaning',
    source: 'Referral',
    requirement: 'Commercial property cleaning',
    budget: 1800,
    status: 'closed-lost',
    createdAt: '2026-01-10',
  },
  {
    id: '20',
    name: 'Donna Young',
    email: 'dyoung@email.com',
    phone: '(555) 000-1111',
    address: '147 Walnut Drive',
    city: 'Glenview',
    state: 'IL',
    service: 'Flooring Repair',
    source: 'Website',
    requirement: 'Hardwood floor restoration',
    budget: 4800,
    status: 'proposal-sent',
    createdAt: '2026-01-09',
  },
]
